version: "3.9"

services:
  permissions-manager:
    build: .
    links:
      - couchdb
  couchdb:
    image: couchdb
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
